# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Tag for the Docker image'
        required: true

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install Dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm test

  approval-for-build:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Request Approval for Build
        uses: actions/github-script@v6
        with:
          script: |
            const reviewers = ["tech-lead-username"];
            const { data: issue } = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "Approval for Build Step",
              body: "Please approve the build step after successful unit tests.",
              assignees: reviewers,
            });
            console.log(`Approval issue created: ${issue.html_url}`);

      - name: Wait for approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ steps.generate_token.outputs.token }}
          approvers: myteam
          minimum-approvals: 1

  build:
    runs-on: ubuntu-latest
    needs: approval-for-build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
    
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
  
      - name: Install Dependencies
        run: npm ci
  
      - name: Build Application
        run: npm run build --if-present
